[colors.primary]
background = '#000000'
foreground = '#C5C9C7'

[colors.normal]
black = '#14171d'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#a292a3'
cyan = '#8ea4a2'
white = '#c8c093'

[colors.bright]
black = '#A4A7A4'
red = '#e46876'
green = '#87a987'
yellow = '#e6c384'
blue = '#7fb4ca'
magenta = '#938aa9'
cyan = '#7aa89f'
white = '#C5C9C7'

[colors.selection]
background = '#393B44'
foreground = '#C5C9C7'

[[colors.indexed_colors]]
index = 16
color = '#b6927b'

[[colors.indexed_colors]]
index = 17
color = '#b98d7b'

[font]
size = 15

[window]
opacity = 1

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
    { key = "Tab", mods = "None", chars = "$" }
]
